'use client'

import { LightsCanvas } from '@/components/lights-canvas'
import { NavScroll } from '@/components/nav-scroll'
import { RevealObserver } from '@/components/reveal-observer'

const WA = 'https://wa.me/5493415111363'

type Kind = 'legal' | 'empresas'

const data = {
  legal: {
    label: 'pragma legal', accent: 'De abogados,<br>para abogados<span class="hl-elec">.</span>', tag: 'Inteligencia Artificial · Estudios, escribanías y áreas legales', switch: 'empresas', switchDesc: 'IA para pymes y equipos de operaciones', other: '/empresas', cross: 'pragma empresas', crossDesc: 'IA para pymes y equipos de operaciones', kind: 'legal' as Kind,
    lede: <>Inteligencia artificial aplicada a tu práctica legal. Ni teoría ni herramientas genéricas: <strong>soluciones concretas, personalizadas y enfocadas en resultados</strong> que se ven en el día a día de tu estudio o tu área legal.</>,
    audience: [['01 · Estudios jurídicos','Litigio y asesoramiento','Escritos que se redactan solos, jurisprudencia en minutos y expedientes que dejan de acumularse.',['Escritos','Jurisprudencia','Expedientes','Plazos']],['02 · Escribanías','Actividad notarial','IA aplicada al trabajo notarial real: estudios de títulos, escrituras y minutas, y toda la documentación registral. Con criterio notarial, no genérico.',['Estudios de títulos','Escrituras y minutas','Documentación registral','Normativa y precedentes']],['03 · Áreas legales in-house','Legal dentro de la empresa','Contratos, compliance y las consultas recurrentes del negocio, resueltas sin frenar la operación.',['Contratos','Compliance','Consultas internas','Societario']]],
    values: [['Desde adentro','Venimos del derecho. Entendemos cómo trabaja un abogado y hablamos tu idioma.'],['A tu medida','Nada de plantillas. Trabajamos sobre tus documentos, flujos y problemas reales.'],['Con resultados','Concreto y medible. Menos tiempo administrativo, más foco en lo que suma.']],
  },
  empresas: {
    label: 'pragma empresas', accent: 'Redefinamos la<br>forma de hacer <em>negocios</em><span class="hl-elec">.</span>', tag: 'Inteligencia Artificial · Pymes y equipos de operaciones', switch: 'legal', switchDesc: 'IA para estudios jurídicos y áreas legales', other: '/legal', cross: 'pragma legal', crossDesc: 'IA para estudios jurídicos y áreas legales', kind: 'empresas' as Kind,
    lede: <>Inteligencia artificial aplicada a la operación de tu empresa. Ni teoría ni herramientas genéricas: <strong>soluciones concretas, personalizadas y enfocadas en resultados</strong> que se ven en el día a día.</>,
    audience: [['01 · Pymes','Operaciones y administración','Procesos más claros, menos tareas repetitivas y más tiempo para hacer crecer el negocio.',['Operaciones','Administración','Procesos','Reportes']],['02 · Equipos comerciales','Ventas y seguimiento','La información correcta, en el momento correcto, sin perder oportunidades por tareas manuales.',['CRM','Seguimiento','Propuestas','Métricas']],['03 · Back-office','El trabajo detrás del negocio','Documentos, consultas internas y procesos ordenados para que el equipo avance más rápido.',['Documentos','Consultas','Procesos','Información']]],
    values: [['Desde adentro','Entendemos cómo funcionan las empresas y dónde se pierde tiempo todos los días.'],['A tu medida','Trabajamos sobre tus documentos, flujos y problemas reales.'],['Con resultados','Concreto y medible. Menos fricción, más capacidad para hacer.']],
  },
} as const

export function VerticalPage({ kind }: { kind: Kind }) {
  const d = data[kind]
  const stages = [['Etapa 01','Formación','Entender la herramienta.','Capacitaciones sobre casos reales de tu práctica: tus expedientes, tus escritos, tus flujos. Tu equipo sale sabiendo hacer, no solo entendiendo qué es.'],['Etapa 02','Implementación','Ver dónde aplicarla.','Detectamos oportunidades reales y construimos herramientas a medida: bases de conocimiento, análisis documental, automatización de escritos y trámites.'],['Etapa 03','Acompañamiento','Evolucionar tu forma de trabajar.','Nos integramos como un área externa de innovación continua: revisamos flujos, proponemos mejoras y mantenemos vivo lo construido. Abono mensual.']]
  return <div className={`pragma-vertical ${kind}`}><NavScroll /><RevealObserver />
    <nav id="nav"><a href="/" className="logo">pragma<span className="logo-dot" /><span className="logo-kind">{kind}</span></a><div className="nav-right"><a className="nav-switch" href={d.other}>Ir a pragma {d.switch} →</a><div className="nav-links"><a href="#para-quien">Para quién</a><a href="#journey">AI Journey</a><a href="#como">Cómo trabajamos</a><a href="#impacto">Impacto</a></div><a className="nav-btn" href={WA}>Contactar →</a></div></nav>
    <main><section id="hero"><div className="hero-bg"><LightsCanvas /></div><div className="hero-top reveal" data-d="1"><div className="hero-tag">{d.tag}</div><a className="hero-top-cta" href={WA}>Agendá una charla <span className="cta-arrow">→</span></a></div><div className="hero-headline reveal" data-d="2"><h1 className="hero-h1" dangerouslySetInnerHTML={{__html:d.accent}} /><p className="hero-lede">{d.lede}</p></div><div className="hero-bottom reveal" data-d="3">{d.values.map(([title,text])=><div className="hero-val" key={title}><span className="hv-mark" /><div className="hv-title">{title}</div><div className="hv-text">{text}</div></div>)}</div></section>
    <section id="para-quien"><div className="aud-header reveal"><div><div className="sh-label">Para quién</div><div className="sh-title">Tres formas de ejercer.<br />El mismo problema de fondo.</div></div><div className="sh-note">Demasiado tiempo en tarea mecánica y poco en el criterio que te distingue.</div></div><div className="aud-grid reveal">{d.audience.map(([k,t,desc,tags])=><div className="aud-cell" key={k}><div className="aud-k">{k}</div><div className="aud-t">{t}</div><div className="aud-d">{desc}</div><div className="aud-tags">{tags.map(tag=><span key={tag}>{tag}</span>)}</div></div>)}</div></section>
    <section id="journey"><div className="journey-header reveal"><div><div className="jh-eyebrow">Nuestra propuesta</div><div className="jh-title">El <em>AI Journey</em>.<br />Tres etapas, una sola dirección.</div></div><div className="jh-note">Formación, implementación y acompañamiento sobre tu operación legal.</div></div><div className="jh-optbar">No es un paquete — podés entrar en cualquier etapa y frenar donde quieras</div><div className="stages reveal">{stages.map(([n,t,k,desc])=><div className="stage" key={n}><div className="stage-l"><span className="stage-n">{n}</span><div className="stage-t">{t}</div></div><div><div className="stage-kicker">{k}</div><div className="stage-desc">{desc}</div></div></div>)}</div></section>
    <section id="impacto"><div className="impact-top reveal"><div className="impact-eyebrow">El impacto</div><h2 className="impact-h2">Menos trabajo mecánico.<br />Más criterio y capacidad.</h2><p className="impact-note">La IA no reemplaza al equipo: le saca de encima lo repetitivo para que dedique su tiempo a lo que de verdad agrega valor. Estas son las áreas donde primero se nota.</p></div><div className="impact-inner reveal">{[['Gestión administrativa','Notificaciones, derivaciones y seguimiento de plazos dejan de comerte la mañana.','Notificaciones · Derivación · Plazos'],['Investigación','Información, análisis y documentación en una fracción del tiempo.','Investigación · Documentos'],['Documentación','Escritos, actas y trámites que se redactan solos, listos para revisar.','Escritos · Actas · Trámites']].map(([a,b,c])=><div className="impact-cell" key={a}><div className="impact-area">{a}</div><div className="impact-desc">{b}</div><div className="impact-source">{c}</div></div>)}</div></section>
    <section id="como"><div className="como-header reveal"><div><div className="sh-label">Cómo trabajamos</div><div className="sh-title">No nos conformamos con una solución:<br />queremos la mejor.</div></div><div className="sh-note">Sabemos por qué la mayoría de las iniciativas de IA no llegan a ningún lado.</div></div><div className="como-grid reveal"><div className="como-col no"><div className="como-lbl">Lo que no vas a encontrar</div>{['Cursos pregrabados','Consultoras que entregan un PDF','Desarrollos desde cero'].map(x=><div className="como-item" key={x}><span className="como-mark">✕</span><span className="como-txt"><span className="strike">{x}</span><span className="como-sub">Soluciones genéricas que nadie termina de usar.</span></span></div>)}</div><div className="como-col si"><div className="como-lbl">Lo que sí</div>{['Formación sobre tus casos reales','Nos quedamos hasta que funcione','No inventamos la rueda'].map(x=><div className="como-item" key={x}><span className="como-mark">→</span><span className="como-txt"><span>{x}</span><span className="como-sub">Trabajamos sobre tu realidad y medimos lo que cambia.</span></span></div>)}</div></div></section>
    <section id="quote"><div className="quote-inner reveal"><div className="quote-eyebrow">Nuestra filosofía</div><blockquote className="quote-text">“La mejor forma de predecir<br />el futuro es <em>crearlo</em>.”</blockquote><div className="quote-author">— Alan Kay</div></div></section>
    <section id="cta"><div className="cta-left reveal"><div className="cta-eyebrow">Hablemos</div><a className="acta" href={WA}>Media hora, sin compromiso.<span className="arw">→</span></a><div className="acta-sub">Si con lo que ya tenés alcanza, te lo decimos.</div></div></section>
    <section id="contacto"><div className="contact-grid reveal"><div><div className="contact-eyebrow">Contacto</div><h2 className="contact-h">Hablemos<span className="dot">.</span></h2><p className="contact-note">Media hora, sin compromiso. Te mostramos qué puede hacer la IA por tu estudio o tu área, con ejemplos de tu práctica. Si con lo que ya tenés alcanza, te lo decimos.</p></div><div className="contact-list"><a className="contact-row" href="mailto:mpansa@bepragma.com.ar"><span className="contact-txt"><span className="lbl">Email</span><span className="val">mpansa@bepragma.com.ar</span></span></a><a className="contact-row" href="mailto:enhidalgo@bepragma.com.ar"><span className="contact-txt"><span className="lbl">Email</span><span className="val">enhidalgo@bepragma.com.ar</span></span></a><a className="contact-row" href={WA}><span className="contact-txt"><span className="lbl">WhatsApp</span><span className="val">+54 9 3415 111 363</span></span></a></div></div></section>
    <a className="crossnav" href={d.other}><div className="crossnav-l"><span className="crossnav-k">¿Buscabas la otra vertical?</span><span className="crossnav-t">{d.cross}</span><span className="crossnav-d">{d.crossDesc}</span></div><span className="crossnav-a">Ir →</span></a><footer><div className="footer-logo">pragma<span className="logo-dot" /></div><div className="footer-links"><a href="#para-quien">Para quién</a><a href="#journey">AI Journey</a><a href="#como">Cómo trabajamos</a><a href="#impacto">Impacto</a><a href="#contacto">Contacto</a><a href={d.other}>pragma {d.switch}</a></div><div className="footer-copy">© 2026 pragma. mpansa@bepragma.com.ar · +54 9 3415 111 363</div></footer></main>
  </div>
}
